=== Caramelian/Quell_Reflect_Projet/Grammaire.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT data (level)+ >
<!ELEMENT level ((length, width, numberOfCoins), ((Anneau)+ | (bloc_Sexue)+ | (Bulle)+ | (case_Verte)+ | (case_Vide)+ | (Mur)+ | (Pic)+ | (Switcher)+)) >
<!ATTLIST level number ID "1" >
<!ELEMENT Anneau (coordinateX, coordinateY, color, partner) >
<!ELEMENT partner (coordinateX, coordinateY, color) >
<!ELEMENT bloc_Sexue (male, coordinateX, coordinateY) >
<!ELEMENT Bulle (selection, order, coordinateX, coordinateY) >
<!ELEMENT case_Verte (coordinateX, coordinateY) >
<!ELEMENT case_Vide (coordinateX, coordinateY, piece) >
<!ELEMENT Mur (jewel, coordinateX, coordinateY) >
<!ELEMENT Pic (up, down, right, left, color, coordinateX, coordinateY) >
<!ELEMENT length (#PCDATA) >
<!ELEMENT width (#PCDATA) >
<!ELEMENT numberOfCoins (#PCDATA) >
<!ELEMENT coordinateX (#PCDATA) >
<!ELEMENT coordinateY (#PCDATA) >
<!ELEMENT color (#PCDATA) >
<!ELEMENT male (#PCDATA) >
<!ELEMENT selection (#PCDATA) >
<!ELEMENT order (#PCDATA) >
<!ELEMENT piece (#PCDATA) >
<!ELEMENT jewel (#PCDATA) >
<!ELEMENT up (#PCDATA) >
<!ELEMENT down (#PCDATA) >
<!ELEMENT right (#PCDATA) >
<!ELEMENT left (#PCDATA) >

=== Caramelian/Quell_Reflect_Projet/Tableau.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE data SYSTEM "Grammaire.dtd">

<data>
	<level number="1">
		<length> 15 </length>
		<width> 8 </width>
		<numberOfCoins> 2 </numberOfCoins>
		<numberOfMovingObjects> 2 </numberOfMovingObjects>
		<Anneau>
			<coordinateX> 2 </coordinateX>
			<coordinateY> 14 </coordinateY>
			<color> 1 </color>
			<partner>
				<coordinateX> 7 </coordinateX>
				<coordinateY> 1 </coordinateY>
				<color> 1 </color>
			</partner>
		</Anneau>
		<bloc_Sexue>
			<male> true </male>
			<coordinateX> 4 </coordinateX>
			<coordinateY> 3 </coordinateY>
		</bloc_Sexue>
		<Bulle>
			<selection> true </selection>
			<order> 1 </order>
			<coordinateX> 6 </coordinateX>
			<coordinateY> 2 </coordinateY>
		</Bulle>
		<case_Verte>
			<coordinateX> 4 </coordinateX>
			<coordinateY> 4 </coordinateY>
		</case_Verte>
		<case_Verte>
			<coordinateX> 4 </coordinateX>
			<coordinateY> 6 </coordinateY>
		</case_Verte>
		<case_Verte>
			<coordinateX> 4 </coordinateX>
			<coordinateY> 7 </coordinateY>	
		</case_Verte>
		<case_Verte>
			<coordinateX> 4 </coordinateX>
			<coordinateY> 10 </coordinateY>	
		</case_Verte>
		<case_Verte>
			<coordinateX> 5 </coordinateX>
			<coordinateY> 13 </coordinateY>	
		</case_Verte>
		<case_Verte>
			<coordinateX> 3 </coordinateX>
			<coordinateY> 13 </coordinateY>	
		</case_Verte>
		<case_Vide>
			<coordinateX> 1 </coordinateX>
			<coordinateY> 2 </coordinateY>
			<piece> false </piece>
		</case_Vide>
		<case_Vide>
			<coordinateX> 1 </coordinateX>
			<coordinateY> 3 </coordinateY>
			<piece> false </piece>
		</case_Vide>
		<case_Vide>
			<coordinateX> 1 </coordinateX>
			<coordinateY> 4 </coordinateY>
			<piece> false </piece>
		</case_Vide>
		<case_Vide>
			<coordinateX> 1 </coordinateX>
			<coordinateY> 8 </coordinateY>
			<piece> false </piece>
		</case_Vide>
		<case_Vide>
			<coordinateX> 1 </coordinateX>
			<coordinateY> 11 </coordinateY>
			<piece> false </piece>
		</case_Vide>
		<case_Vide>
			<coordinateX> 2 </coordinateX>
			<coordinateY> 1 </coordinateY>
			<piece> false </piece>
		</case_Vide>
		<case_Vide>
			<coordinateX> 2 </coordinateX>
			<coordinateY> 2 </coordinateY>
			<piece> false </piece>
		</case_Vide>
		<case_Vide>
			<coordinateX> 2 </coordinateX>
			<coordinateY> 5 </coordinateY>
			<piece> false </piece>
		</case_Vide>
		<case_Vide>
			<coordinateX> 2 </coordinateX>
			<coordinateY> 6 </coordinateY>
			<piece> false </piece>
		</case_Vide>
		<case_Vide>
			<coordinateX> 2 </coordinateX>
			<coordinateY> 7 </coordinateY>
			<piece> false </piece>
		</case_Vide>
		<case_Vide>
			<coordinateX> 2 </coordinateX>
			<coordinateY> 8 </coordinateY>
			<piece> false </piece>
		</case_Vide>
		<case_Vide>
			<coordinateX> 2 </coordinateX>
			<coordinateY> 10 </coordinateY>
			<piece> false </piece>
		</case_Vide>
		<case_Vide>
			<coordinateX> 2 </coordinateX>
			<coordinateY> 11 </coordinateY>
			<piece> false </piece>
		</case_Vide>
		<case_Vide>
			<coordinateX> 2 </coordinateX>
			<coordinateY> 12 </coordinateY>
			<piece> false </piece>
		</case_Vide>
		<case_Vide>
			<coordinateX> 2 </coordinateX>
			<coordinateY> 13 </coordinateY>
			<piece> true </piece>
		</case_Vide>
		<case_Vide>
			<coordinateX> 3 </coordinateX>
			<coordinateY> 1 </coordinateY>
			<piece> false </piece>
		</case_Vide>
		<case_Vide>
			<coordinateX> 3 </coordinateX>
			<coordinateY> 3 </coordinateY>
			<piece> false </piece>
		</case_Vide>
		<case_Vide>
			<coordinateX> 3 </coordinateX>
			<coordinateY> 5 </coordinateY>
			<piece> false </piece>
		</case_Vide>
		<case_Vide>
			<coordinateX> 3 </coordinateX>
			<coordinateY> 8 </coordinateY>
			<piece> false </piece>
		</case_Vide>
		<case_Vide>
			<coordinateX> 3 </coordinateX>
			<coordinateY> 9 </coordinateY>
			<piece> false </piece>
		</case_Vide>
		<case_Vide>
			<coordinateX> 3 </coordinateX>
			<coordinateY> 10 </coordinateY>
			<piece> false </piece>
		</case_Vide>
		<case_Vide>
			<coordinateX> 4 </coordinateX>
			<coordinateY> 1 </coordinateY>
			<piece> false </piece>
		</case_Vide>
		<case_Vide>
			<coordinateX> 4 </coordinateX>
			<coordinateY> 2 </coordinateY>
			<piece> false </piece>
		</case_Vide>
		<case_Vide>
			<coordinateX> 4 </coordinateX>
			<coordinateY> 3 </coordinateY>
			<piece> false </piece>
		</case_Vide>
		<case_Vide>
			<coordinateX> 4 </coordinateX>
			<coordinateY> 5 </coordinateY>
			<piece> false </piece>
		</case_Vide>
		<case_Vide>
			<coordinateX> 4 </coordinateX>
			<coordinateY> 8 </coordinateY>
			<piece> false </piece>
		</case_Vide>
		<case_Vide>
			<coordinateX> 4 </coordinateX>
			<coordinateY> 9 </coordinateY>
			<piece> false </piece>
		</case_Vide>
		<case_Vide>
			<coordinateX> 4 </coordinateX>
			<coordinateY> 11 </coordinateY>
			<piece> false </piece>
		</case_Vide>
		<case_Vide>
			<coordinateX> 4 </coordinateX>
			<coordinateY> 12 </coordinateY>
			<piece> false </piece>
		</case_Vide>
		<case_Vide>
			<coordinateX> 4 </coordinateX>
			<coordinateY> 13 </coordinateY>
			<piece> false </piece>
		</case_Vide>
		<case_Vide>
			<coordinateX> 4 </coordinateX>
			<coordinateY> 14 </coordinateY>
			<piece> false </piece>
		</case_Vide>
		<case_Vide>
			<coordinateX> 5 </coordinateX>
			<coordinateY> 1 </coordinateY>
			<piece> false </piece>
		</case_Vide>
		<case_Vide>
			<coordinateX> 5 </coordinateX>
			<coordinateY> 2 </coordinateY>
			<piece> false </piece>
		</case_Vide>
		<case_Vide>
			<coordinateX> 5 </coordinateX>
			<coordinateY> 3 </coordinateY>
			<piece> false </piece>
		</case_Vide>
		<case_Vide>
			<coordinateX> 5 </coordinateX>
			<coordinateY> 5 </coordinateY>
			<piece> false </piece>
		</case_Vide>
		<case_Vide>
			<coordinateX> 5 </coordinateX>
			<coordinateY> 9 </coordinateY>
			<piece> false </piece>
		</case_Vide>
		<case_Vide>
			<coordinateX> 5 </coordinateX>
			<coordinateY> 11 </coordinateY>
			<piece> false </piece>
		</case_Vide>
		<case_Vide>
			<coordinateX> 6 </coordinateX>
			<coordinateY> 2 </coordinateY>
			<piece> false </piece>
		</case_Vide>
		<case_Vide>
			<coordinateX> 6 </coordinateX>
			<coordinateY> 3 </coordinateY>
			<piece> false </piece>
		</case_Vide>
		<case_Vide>
			<coordinateX> 6 </coordinateX>
			<coordinateY> 4 </coordinateY>
			<piece> false </piece>
		</case_Vide>
		<case_Vide>
			<coordinateX> 6 </coordinateX>
			<coordinateY> 5 </coordinateY>
			<piece> false </piece>
		</case_Vide>
		<case_Vide>
			<coordinateX> 6 </coordinateX>
			<coordinateY> 7 </coordinateY>
			<piece> false </piece>
		</case_Vide>
		<case_Vide>
			<coordinateX> 6 </coordinateX>
			<coordinateY> 8 </coordinateY>
			<piece> false </piece>
		</case_Vide>
		<case_Vide>
			<coordinateX> 6 </coordinateX>
			<coordinateY> 9 </coordinateY>
			<piece> false </piece>
		</case_Vide>
		<case_Vide>
			<coordinateX> 6 </coordinateX>
			<coordinateY> 10 </coordinateY>
			<piece> false </piece>
		</case_Vide>
		<case_Vide>
			<coordinateX> 6 </coordinateX>
			<coordinateY> 11 </coordinateY>
			<piece> false </piece>
		</case_Vide>
		<case_Vide>
			<coordinateX> 6 </coordinateX>
			<coordinateY> 13 </coordinateY>
			<piece> true </piece>
		</case_Vide>
		<case_Vide>
			<coordinateX> 7 </coordinateX>
			<coordinateY> 2 </coordinateY>
			<piece> false </piece>
		</case_Vide>
		<case_Vide>
			<coordinateX> 7 </coordinateX>
			<coordinateY> 5 </coordinateY>
			<piece> false </piece>
		</case_Vide>
		<case_Vide>
			<coordinateX> 7 </coordinateX>
			<coordinateY> 6 </coordinateY>
			<piece> false </piece>
		</case_Vide>
		<case_Vide>
			<coordinateX> 7 </coordinateX>
			<coordinateY> 7 </coordinateY>
			<piece> false </piece>
		</case_Vide>
		<case_Vide>
			<coordinateX> 7 </coordinateX>
			<coordinateY> 9 </coordinateY>
			<piece> false </piece>
		</case_Vide>
		<case_Vide>
			<coordinateX> 8 </coordinateX>
			<coordinateY> 1 </coordinateY>
			<piece> false </piece>
		</case_Vide>
		<case_Vide>
			<coordinateX> 8 </coordinateX>
			<coordinateY> 2 </coordinateY>
			<piece> false </piece>
		</case_Vide>
		<case_Vide>
			<coordinateX> 8 </coordinateX>
			<coordinateY> 3 </coordinateY>
			<piece> false </piece>
		</case_Vide>
		<case_Vide>
			<coordinateX> 8 </coordinateX>
			<coordinateY> 4 </coordinateY>
			<piece> false </piece>
		</case_Vide>
		<case_Vide>
			<coordinateX> 8 </coordinateX>
			<coordinateY> 8 </coordinateY>
			<piece> false </piece>
		</case_Vide>
		<case_Vide>
			<coordinateX> 8 </coordinateX>
			<coordinateY> 9 </coordinateY>
			<piece> false </piece>
		</case_Vide>
		<case_Vide>
			<coordinateX> 8 </coordinateX>
			<coordinateY> 10 </coordinateY>
			<piece> false </piece>
		</case_Vide>
		<case_Vide>
			<coordinateX> 8 </coordinateX>
			<coordinateY> 11 </coordinateY>
			<piece> false </piece>
		</case_Vide>
		<Mur>
			<jewel> false </jewel>
			<coordinateX> 1 </coordinateX>
			<coordinateY> 1 </coordinateY>
		</Mur>
		<Mur>
			<jewel> false </jewel>
			<coordinateX> 1 </coordinateX>
			<coordinateY> 5 </coordinateY>
		</Mur>
		<Mur>
			<jewel> false </jewel>
			<coordinateX> 1 </coordinateX>
			<coordinateY> 6 </coordinateY>
		</Mur>
		<Mur>
			<jewel> false </jewel>
			<coordinateX> 1 </coordinateX>
			<coordinateY> 7 </coordinateY>
		</Mur>
		<Mur>
			<jewel> false </jewel>
			<coordinateX> 1 </coordinateX>
			<coordinateY> 9 </coordinateY>
		</Mur>
		<Mur>
			<jewel> false </jewel>
			<coordinateX> 1 </coordinateX>
			<coordinateY> 10 </coordinateY>
		</Mur>
		<Mur>
			<jewel> false </jewel>
			<coordinateX> 1 </coordinateX>
			<coordinateY> 12 </coordinateY>
		</Mur>
		<Mur>
			<jewel> false </jewel>
			<coordinateX> 1 </coordinateX>
